First we will get all the data from the Neo4j instance into a polars dataframe.

In [7]:
import polars as pl

df = pl.read_csv("neo4j_small_sample.csv")
df.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ source_id ┆ source_la ┆ source_pr ┆ rel_id    ┆ … ┆ rel_props ┆ target_id ┆ target_la ┆ target_p │
│ ---       ┆ bels      ┆ ops       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ bels      ┆ rops     │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4:5542f03 ┆ [CVE]     ┆ {         ┆ 5:5542f03 ┆ … ┆ {}        ┆ 4:5542f03 ┆ [Referenc ┆ {        │
│ 7-95a3-4c ┆           ┆ cvss_vers ┆ 7-95a3-4c ┆   ┆           ┆ 7-95a3-4c ┆ e]        ┆ created_ │
│ cf-824f-d ┆           ┆ ion: V2,  ┆ cf-824f-d ┆   ┆           ┆ cf-824f-d ┆           ┆ at: 2025 │
│ 750…      ┆           ┆   cvss_s… ┆ 750…      ┆   ┆           ┆ 750…      ┆           ┆ -12-21T2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1:…      │
│ 4:5542f03 ┆ [CVE]     ┆ {         ┆ 5:5542f03 ┆ … ┆ {}        ┆ 4:5542f03 ┆ [Referenc ┆ {        │
│ 7-95a3-4c ┆           ┆ cvss_vers ┆ 7-95a3-4c ┆   ┆           ┆ 7-95a3-4c ┆ e]        ┆ created_ │
│ cf-824f-d ┆           ┆ ion: V2,  ┆ cf-824f-d ┆   ┆           ┆ cf-824f-d ┆           ┆ at: 2025 │
│ 750…      ┆           ┆   cvss_s… ┆ 750…      ┆   ┆           ┆ 750…      ┆           ┆ -12-21T2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1:…      │
│ 4:5542f03 ┆ [CVE]     ┆ {         ┆ 5:5542f03 ┆ … ┆ {}        ┆ 4:5542f03 ┆ [Referenc ┆ {        │
│ 7-95a3-4c ┆           ┆ cvss_vers ┆ 7-95a3-4c ┆   ┆           ┆ 7-95a3-4c ┆ e]        ┆ created_ │
│ cf-824f-d ┆           ┆ ion: V2,  ┆ cf-824f-d ┆   ┆           ┆ cf-824f-d ┆           ┆ at: 2025 │
│ 750…      ┆           ┆   cvss_s… ┆ 750…      ┆   ┆           ┆ 750…      ┆           ┆ -12-21T2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1:…      │
│ 4:5542f03 ┆ [CVE]     ┆ {         ┆ 5:5542f03 ┆ … ┆ {}        ┆ 4:5542f03 ┆ [Device]  ┆ {        │
│ 7-95a3-4c ┆           ┆ cvss_vers ┆ 7-95a3-4c ┆   ┆           ┆ 7-95a3-4c ┆           ┆ device_n │
│ cf-824f-d ┆           ┆ ion: V2,  ┆ cf-824f-d ┆   ┆           ┆ cf-824f-d ┆           ┆ ame: Mic │
│ 750…      ┆           ┆   cvss_s… ┆ 750…      ┆   ┆           ┆ 750…      ┆           ┆ rosoft   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Xbo…     │
│ 4:5542f03 ┆ [CVE]     ┆ {         ┆ 5:5542f03 ┆ … ┆ {}        ┆ 4:5542f03 ┆ [Referenc ┆ {        │
│ 7-95a3-4c ┆           ┆ cvss_vers ┆ 7-95a3-4c ┆   ┆           ┆ 7-95a3-4c ┆ e]        ┆ created_ │
│ cf-824f-d ┆           ┆ ion: V2,  ┆ cf-824f-d ┆   ┆           ┆ cf-824f-d ┆           ┆ at: 2025 │
│ 750…      ┆           ┆   cvss_s… ┆ 750…      ┆   ┆           ┆ 750…      ┆           ┆ -12-21T2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1:…      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Explore the Data
Let's see how many unique CPEs or "TrueNames" we have.

In [13]:
cpes = df.filter(pl.col("source_labels") == "[TrueName]")
cpes.unique(subset=["source_props"]).count()

shape: (1, 9)
┌───────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ source_id ┆ source_lab ┆ source_pro ┆ rel_id ┆ … ┆ rel_props ┆ target_id ┆ target_la ┆ target_pr │
│ ---       ┆ els        ┆ ps         ┆ ---    ┆   ┆ ---       ┆ ---       ┆ bels      ┆ ops       │
│ u32       ┆ ---        ┆ ---        ┆ u32    ┆   ┆ u32       ┆ u32       ┆ ---       ┆ ---       │
│           ┆ u32        ┆ u32        ┆        ┆   ┆           ┆           ┆ u32       ┆ u32       │
╞═══════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 20        ┆ 20         ┆ 20         ┆ 20     ┆ … ┆ 20        ┆ 20        ┆ 20        ┆ 20        │
└───────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Prompt Template
Okay we're going to take a step back from the Polars dataset now to look at what our prompt template will look like, and ultmiately what data we need to fill it with.

In [ ]:
from langchain_core.prompts import ChatPromptTemplate

# for the model that will be trained
SYSTEM_PROMPT = """You are a helpful and friendly home technology assistant. \
    Your goal is to analyze device reports and provide a simple, non-technical summary and a step-by-step guide for an average person.
    
    **Critical Constraints & Rules:**

1.  **No Jargon:** NEVER use technical terms like "CVE," "vulnerability," "exploit," "malicious," "command injection," "brute-force," "firmware," or "credentials."
2.  **Friendly Terminology:** Instead of the terms above, use words like "security issue," "glitch," "software bug," "login details," "update," or "settings."
3.  **Reassurance:** Always assure the user they have done nothing wrong.
4.  **Safe Password Advice:** NEVER suggest a specific password (like "SecurePass2023") or specific PIN (like "12345678"). Instead, tell the user to choose a "long, unique password" or a "random PIN." DO NOT use `(eg, ADVICE)` anywhere in your response.
5.  **Clickable Links:** If a device IP address is provided, you MUST format it as a clickable Markdown link, like this: `[192.168.1.1](http://192.168.1.1)`. Do not use backticks (`) or code blocks for the link.
6.  **Focus on the Fix:** Do not explain *how* the glitch works (e.g., do not mention "code execution"). Just explain that an update or setting change fixes it."""

training_prompt = ChatPromptTemplate.from_template("""\

"""
)